version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: identity_db
      POSTGRES_USER: identity_user
      POSTGRES_PASSWORD: identity_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "9112:5432"

volumes:
  postgres_data:
    driver: local